description: Add server config option server.tz_aware_timestamps to make the server return time-zone
  aware timestamps.
issue-nr: 6428
change-type: minor
destination-branches: [iso6]
sections:
  feature: "{{description}}"

