---
description: 'Mark parameters in the path of an endpoint using `<param>` instead of `{param}` in the openapi documentation.'
change-type: patch
destination-branches: [master, iso8, iso7]
sections:
  minor-improvement: "{{description}}"
