version: '3'
services:
    inmanta:
        build:
            context: .
        ports:
            - "8888:8888"
        links:
            - postgres
        volumes:
            - inmanta-data:/var/lib/inmanta

    postgres:
        image: postgres:10

volumes:
    inmanta-data:
