---
description: The 'dashboard' section is no longer supported for configuration options. The 'web-ui' section should now be used instead for configuration options related to web interfaces.
change-type: major
issue-nr: 317
issue-repo: inmanta-ui
destination-branches: [master]
sections:
  deprecation-note: "{{description}}"
