---
description: The 'dashboard' section is being deprecated. The 'web-ui' section should now be used instead for configuration options related to web interfaces.
change-type: minor
issue-nr: 317
issue-repo: inmanta-ui
destination-branches: [iso5]
sections:
  deprecation-note: "{{description}}"
