change-type: patch
issue-nr: 3668
description: Ensure processes forked by Inmanta commands load the same config folder as their parent process
destination-branches:
- master
- iso5
- iso4
sections:
    feature: "{{description}}"
