description: Remove the autostart_agent_interval and autostart_splay environment settings
issue-nr: 6084
change-type: major
destination-branches: [master]
sections:
  deprecation-note: "{{description}}"
