description: Add server config option server.tz_aware_timestamps to make the server return time-zone
  aware timestamps.
issue-nr: 6428
change-type: major
destination-branches: [iso7, master]
sections:
  feature: "{{description}}"

