description: Documentation PR for the new pip config and its behaviour. This PR centralizes the change entries.
issue-nr: 6518
change-type: major
destination-branches: [master]
sections:
  feature: "A project-wide pip configuration can be set through the project.yml pip section."
  upgrade-note: "Reworked the orchestrator's pip configuration: please refer to the [migration guide](reference/projectyml.html#migrate-to-project-wide-pip-config) to move to a project-wide pip configuration."
