description: >
  In the configuration reference page, for each configuration option, the
  corresponding environment variable is now displayed.
issue-nr: 8303
change-type: patch
destination-branches: [master, iso7]
