---
description: "Add support for extensions to register their environment settings via the `register_environment_settings` method in the `extension.py` file of the extension."
issue-nr: 1366
issue-repo: irt
change-type: minor
destination-branches: [iso5]
sections:
  feature: "{{description}}"
  deprecation-note: "The `inmanta.server.services.environmentservice.register_setting` method, used by the extensions to register environment settings, has been deprecated. The `register_environment_settings` method in the `extension.py` of the extension has to be used instead."
