---
description: The hardcoded agent backoff time is now configurable using the `config.agent_get_resource_backoff` config option. The default value was changed from five to three seconds.
change-type: patch
destination-branches: [master, iso6]
sections:
  minor-improvement: "{{description}}"
