---
description: The `compiled_environments` fixture performed concurrent compilations on the same source project. This PR ensures that each environment has a separate source directory.
change-type: patch
destination-branches: [master, iso6, iso5]
