---
description: Fix bug that causes literal values to be rendered incorrectly in the OpenAPI documentation.
issue-nr: 1586
issue-repo: inmanta-lsm
change-type: patch
destination-branches: [master, iso7, iso6]
sections:
  bugfix: "{{description}}"
