[metadata]
name = inmanta-module-dummy-future
version = 1.0
description = A v2 module that defines a reference behind each of its two extras
license = Apache 2.0
author = Inmanta <code@inmanta.com>

[options]
zip_safe=False
include_package_data=True
packages=find_namespace:

[options.extras_require]
used =
    dummy-future-used-dep
    inmanta-module-dummy-future-used-mod
unused =
    dummy-future-unused-dep
    inmanta-module-dummy-future-unused-mod
