import typing
from typing import Any

def quote(identifier: str, is_html_string: Any=..., is_valid_id: Any=..., dot_keywords: Any=..., escape_unescaped_quotes: Any=...) -> str: ...
def quote_edge(identifier: str) -> str: ...
def a_list(label: typing.Optional[str]=..., kwargs: Any=..., attributes: Any=...) -> str: ...
def attr_list(label: typing.Optional[str]=..., kwargs: Any=..., attributes: Any=...) -> str: ...
def escape(s: str) -> NoHtml: ...

class NoHtml(str): ...

def nohtml(s: str) -> NoHtml: ...
