description: Fix issue where log file config was not correctly applied when specified via the config file
issue-nr: 8858
change-type: patch
destination-branches: [iso7]
sections:
  bugfix: "{{description}}"

