[metadata]
name = inmanta-module-helper-consumer-module
version = 1.0
description = A v2 module whose handler reuses plugin code from helper_module
license = Apache 2.0
author = Inmanta <code@inmanta.com>

[options]
zip_safe=False
include_package_data=True
packages=find_namespace:
install_requires =
    inmanta-module-helper-module
