from typing import Any, Sequence, Union, Callable


class Texttable:
    BORDER: int
    HEADER: Any
    HLINES: Any
    VLINES: Any
    def __init__(self, max_width: int = ...) -> None: ...
    def set_deco(self, deco: int ) -> None: ...
    def set_cols_dtype(self, array: Sequence[Union[str, Callable[[object], str]]]) -> None: ...
    def header(self, array: Sequence[str]) -> None: ...
    def add_row(self, array: Sequence[Union[str, bool, int, float]]) -> None: ...
    def draw(self) -> str: ...
