from typing import Any, Optional

NEW_TYPING: Any
WITH_LITERAL: bool
WITH_CLASSVAR: bool
LEGACY_TYPING: bool

def is_generic_type(tp: Any) -> bool: ...
def is_callable_type(tp: Any) -> bool: ...
def is_tuple_type(tp: Any) -> bool: ...
def is_optional_type(tp: Any) -> bool: ...
def is_union_type(tp: Any) -> bool: ...
def is_literal_type(tp: Any) -> bool: ...
def is_typevar(tp: Any) -> bool: ...
def is_classvar(tp: Any) -> bool: ...
def is_new_type(tp: Any) -> bool: ...
def is_forward_ref(tp: Any) -> bool: ...
