# Stubs for asyncpg.transaction (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import enum
from typing import Any, Optional, Type, cast
from types import TracebackType


class TransactionState(enum.Enum):
    NEW =  cast(int, ...)
    STARTED =  cast(int, ...)
    COMMITTED =  cast(int, ...)
    ROLLEDBACK =  cast(int, ...)
    FAILED =  cast(int, ...)

ISOLATION_LEVELS: Any

class Transaction(object):
    async def __aenter__(self) -> None: ...
    async def __aexit__(self, exc_type: Optional[Type[BaseException]],
                      exc_value: Optional[BaseException],
                      traceback: Optional[TracebackType]) -> Optional[bool]: ...
    async def start(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
