# Stubs for asyncpg.types (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from asyncpg.pgproto.types import BitString as BitString, Box as Box, Circle as Circle, Line as Line, LineSegment as LineSegment, Path as Path, Point as Point, Polygon as Polygon
from collections import namedtuple
from typing import Any, Optional

Type = namedtuple('Type', ['oid', 'name', 'kind', 'schema'])

Attribute = namedtuple('Attribute', ['name', 'type'])

ServerVersion = namedtuple('ServerVersion', ['major', 'minor', 'micro', 'releaselevel', 'serial'])

class Range: ...

# Names in __all__ with no definition:
#   Attribute
#   ServerVersion
#   Type
