# Stubs for asyncpg.types (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from asyncpg.pgproto.types import BitString as BitString, Box as Box, Circle as Circle, Line as Line, LineSegment as LineSegment, Path as Path, Point as Point, Polygon as Polygon
from collections import namedtuple
from typing import Any, Optional

Type = namedtuple('Type', ['oid', 'name', 'kind', 'schema'])

Attribute = namedtuple('Attribute', ['name', 'type'])

ServerVersion = namedtuple('ServerVersion', ['major', 'minor', 'micro', 'releaselevel', 'serial'])

class Range:
    def __init__(self, lower: Optional[Any] = ..., upper: Optional[Any] = ..., *, lower_inc: bool = ..., upper_inc: bool = ..., empty: bool = ...) -> None: ...
    @property
    def lower(self): ...
    @property
    def lower_inc(self): ...
    @property
    def lower_inf(self): ...
    @property
    def upper(self): ...
    @property
    def upper_inc(self): ...
    @property
    def upper_inf(self): ...
    @property
    def isempty(self): ...
    def __bool__(self): ...
    def __eq__(self, other: Any): ...
    def __hash__(self): ...

# Names in __all__ with no definition:
#   Attribute
#   ServerVersion
#   Type
