---
description: Fix bug in the serialization of the ConfigurationModel dao.
change-type: patch
destination-branches: [master, iso6, iso5, iso4]
sections:
  bugfix: "Fix bug where the 'done' field of a model version returned by the `GET /version` or the `GET /version/<id>` API endpoint decrements when a repair run of an agent changes the state of the resource to deploying again."
