[metadata]
name = inmanta-module-module-with-extras
version = 1.0
description = A v2 module that defines a reference behind each of its two extras
license = Apache 2.0
author = Inmanta <code@inmanta.com>

[options]
zip_safe=False
include_package_data=True
packages=find_namespace:

[options.extras_require]
used =
    module-with-extras-used-dep
    inmanta-module-module-with-extras-used-mod
unused =
    module-with-extras-unused-dep
    inmanta-module-module-with-extras-unused-mod
