from pydantic import JsonValue


class JSONPath:
    def find(self, data: JsonValue) -> JsonValue: ...
    def find_or_create(self, data: JsonValue) -> JsonValue: ...
    def update(self, data: JsonValue, val: object) -> JsonValue: ...
    def update_or_create(self, data: JsonValue, val: object) -> JsonValue: ...
    # def filter(self, fn, data) -> None: ...
    # def child(self, child): ...
    # def make_datum(self, value): ..
